import {getUserAchievements, getUserProfile, givePointsForActivity} from "../../dbUtils.js";
import {MessageFlags} from "discord.js";
import sendCharacterList from "../../generateCharactersListImage.js";

const tempMessageStorage = new Map();

/**
 * Handles the interaction for the "Хочу в рейд" button. This function validates user input, checks for duplicate interaction, verifies user profile data,
 * and sends a raid request to the specified "seller" user.
 *
 * @param {Object} interaction - The interaction object generated by the user action. Contains details about the user and custom interaction ID.
 * @param {Object} pool - The database connection pool used for querying the database.
 * @param {Object} client - The bot client instance used for communicating with Discord API.
 *
 * Validates the interaction by checking:
 * - Whether the user has already interacted with the message.
 * - Whether the user is attempting to send a request to their own ID.
 * - Whether the user has a valid profile and characters.
 *
 * If valid, obtains additional user information including their profile and achievements, and sends the raid request to the seller.
 * Handles edge cases such as missing profiles, missing characters, and duplicate interactions.
 * Temporarily stores the interaction message ID and user interaction to prevent repeat actions, with a timeout to clear stored data.
 */
export default async function (interaction) {
    // Кнопка "Хочу в рейд"
    if (tempMessageStorage.has(interaction.message.id)
        && tempMessageStorage.get(interaction.message.id).includes(interaction.user.id)) {
        console.log("Пользователь уже взаимодействовал с этим сообщением", interaction.message.id, interaction.user.id)
        return await interaction.reply({content: "Вы уже взаимодействовали с этим сообщением", flags: MessageFlags.Ephemeral});
    }

    const [, , sellerId, type] = interaction.customId.split('_');

    if (interaction.user.id === sellerId) {
        return interaction.reply({
            content: '🚫 Вы не можете отправить заявку самому себе.',
            flags: MessageFlags.Ephemeral
        });
    }

    const userProfile = await getUserProfile(interaction.user.id);

    if (!userProfile) {
        return interaction.reply({
            content: "Для использования кнопки 'Хочу в рейд' необходимо иметь заполненный профиль.",
            flags: MessageFlags.Ephemeral
        });
    }

    if (!userProfile.characters.length) {
        await interaction.reply({content: "Не найдены персонажи", flags: MessageFlags.Ephemeral})
        console.error("Не найдены персонажи для пользователя", interaction.user.id);
        return;
    }

    const seller = await client.users.fetch(sellerId);

    if (seller) {
        const achievements = await getUserAchievements(interaction.user.id);
        await sendCharacterList(interaction, `Игрок: <@${interaction.user.id}> отправил запрос на вступление в рейд в качестве ${type === 'dd' ? '**ДД**' : '**Саппорта**'}\n:peacock: **Имя:** ${userProfile.name || 'Не указано'}\n`, userProfile.characters, seller, achievements);
        interaction.reply({content: "Запрос отправлен", flags: MessageFlags.Ephemeral});
        tempMessageStorage.set(interaction.message.id, []);
        tempMessageStorage.get(interaction.message.id).push(interaction.user.id);
        await givePointsForActivity(pool, interaction.user.id, 3);
    }

    setTimeout(() => tempMessageStorage.delete(interaction.message.id), 5 * 60 * 1000);
}